### ISSUE TITLE
TypeError:  PerovskiteBuilder.generate_homogeneous_layer_charge_1() takes 8 positional arguments but 9 were given

### ISSUE THREAD

**Issue by shriramc1** [WillBaldwin0/LDHP-builder#3]
With the minimal script pasted below, I'm running into the following error:

TypeError: PerovskiteBuilder.generate_homogeneous_layer_charge_1() takes 8 positional arguments but 9 were given

from LDHPbuilder.perovskite_builder import OrganicMolecule, InorganicMonolayer, PerovskiteBuilder
import numpy as np
import ase.io
from ase.io import read

monolayer = InorganicMonolayer.from_species_specification('Pb', 'I', 2)
print(monolayer)

new = read('alanine.xyz')
# make the OrganicMolecule object
molecule = OrganicMolecule(
    new,  # ase Atoms
    1  # float
)
print(molecule)

# make samples
pb = PerovskiteBuilder()
np.random.seed(1267)

samples = pb.generate_homogeneous_perovskite_samples(  # homogeneous since just one kind of molecule
    monolayer,
    molecule,
    num_layers=2,  # should be a power of 2, but realistically 4 is already too big
    num_samples=10,
    max_num_attempts=6500,
    # this can be either 'total_thickness' or 'half_thickness'. use half_thickness for long thin +1 molecules
    stacking_method='total_thickness'
)
ase.io.write('samples_PbI.xyz', samples)

alanine.xyz file:

14

N     -0.594617   -1.101133    0.630510
C     -0.307489   -0.099434   -0.354650
C     -0.912135    1.238368   -0.022518
C      1.172908    0.015627   -0.596349
O      1.611156    0.846169   -1.430894
O      2.096587   -0.763633    0.068094
H     -0.020805   -1.952583    0.372780
H     -0.462514   -0.799137    1.601341
H     -1.600711   -1.406649    0.508749
H     -0.736620   -0.416212   -1.329365
H     -1.056710    1.388205    1.072018
H     -1.919878    1.378600   -0.474934
H     -0.232937    2.013062   -0.451274
H      2.963765   -0.341251    0.406494

**Comment by WillBaldwin0** [comment]
just spotted the error - I will make a fix and then run some test today to make sure the system still performs the same on the benchmarks

**Comment by WillBaldwin0** [comment]
This now done - let me know if it works

**Comment by shriramc1** [comment]
Works now thanks! Closing the issue
